name:                local-hackerrank
version:             0.1.0.0
github:              "alepez/local-hackerrank"
license:             BSD3
author:              "Alessandro Pezzato"
maintainer:          "alessandro@pezzato.net"
copyright:           "2019 Alessandro Pezzato"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alepez/local-hackerrank#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  local-hackerrank-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - local-hackerrank

tests:
  local-hackerrank-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - local-hackerrank
    - hspec
    - QuickCheck
